### ISSUE TITLE
npm start can't start

### ISSUE THREAD

**Issue by chaimaech** [bananaoomarang/isomorphic-redux#27]
Hello, 
I have an issue with your example. I tried to follow the tutorial and to clone the project but everytime I run "npm start" it fails, even if I haven't make any modification on any file.

I'm sure I have the latest npm and node versions but I have this error : 

```
chaimae@chaimae:/var/www/html/isomorphic-redux(master)$ npm start

> isomorphic-redux@1.0.0 start /var/www/html/isomorphic-redux
> NODE_ENV=production NODE_PATH=$NODE_PATH:./shared node --harmony .

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventEmitter.listen (/var/www/html/isomorphic-redux/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/var/www/html/isomorphic-redux/index.js:9:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

npm ERR! Linux 3.19.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/home/chaimae/npm-global/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! isomorphic-redux@1.0.0 start: `NODE_ENV=production NODE_PATH=$NODE_PATH:./shared node --harmony .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the isomorphic-redux@1.0.0 start script 'NODE_ENV=production NODE_PATH=$NODE_PATH:./shared node --harmony .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the isomorphic-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production NODE_PATH=$NODE_PATH:./shared node --harmony .
npm ERR! You can get their info via:
npm ERR!     npm owner ls isomorphic-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/isomorphic-redux/npm-debug.log
```

I'm a newbie to React and REdux and all this but I'm willing to learn so please don't consider it as a stupid question (eveni if it is :D)

Thank you in advance =)

**Comment by bananaoomarang** [comment]
It looks like something is already bound to `localhost:3000`. If it's a previous version of this which is forked you can try `killall node` at the command line, then try running again.

Otherwise the easiest way would just be reboot the computer :P

**Comment by chaimaech** [comment]
Hello @bananaoomarang !
I did it twice without results but it turned out to be some NODE_PATH variables I added for another REACT tutorial... It works just fine, sorry for that :D (I tried to get it work for about 3 hours before posting this issue ^^)

Thank you for your quick reply ^__^
