### ISSUE TITLE
Trouble with BrowserHistory

### ISSUE THREAD

**Issue by kirbyk** [bananaoomarang/isomorphic-redux#9]
I'm receiving the following error when I run `npm run dev`.

```
ERROR in ./client/index.jsx
Module not found: Error: Cannot resolve module 'react-router/lib/BrowserHistory' in /Users/kirbykohlmorgen/scratch/isomorphic-redux/client
 @ ./client/index.jsx 15:36-78
```

I'm also getting this related error:

```
Error: Cannot find module 'react-router/lib/Location'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kirbykohlmorgen/scratch/isomorphic-redux/server.jsx:3:47)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/kirbykohlmorgen/scratch/isomorphic-redux/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (/Users/kirbykohlmorgen/scratch/isomorphic-redux/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by bananaoomarang** [comment]
Assuming https://github.com/bananaoomarang/isomorphic-redux/pull/10 fixed this
